server:
  port: 8787
spring:
  application:
    name: "Sample-blog-website"
  datasource:
    url: jdbc:postgresql://localhost:5432/BlogSSU 
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vetka6.30@gmail.com
    password: pbhw bxmu vwhx gsck
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true